spring: 
  profiles:
    active:
    - dev
---
server: 
  port: 7001
spring:
  profiles: dev
  application:
      name: parentproject-springcloud-config-client-6001
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 7001
spring:
  profiles: test
  application:
      name: parentproject-springcloud-config-client-6001
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/